# Generated by Django 4.2.8 on 2023-12-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_data_modificata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='follows',
        ),
    ]
